### ISSUE TITLE
Clock resetting

### ISSUE THREAD

**Issue by Barkingmad15** [danielchalmers/DesktopClock#2]
First off, thank-you for your work on a useful utility :)

(quick edit, by moving the desktopclock.exe away from my C: drive root into another directory, the advanced settings button now brings up a notepad doc with the code, but it does not update with position, font & other personalisations)

I used the installclock.msi & set it up as I like, then clicked the start with PC. The clock does start with PC but each day the personalisations are reset, so each day it starts in the top left no matter where I position it & also the colour & background settings reset. The start with PC option is also unchecked at this point. Not sure if I am missing something obvious or of this is a helpful report. If I click on advanced settings, the option does nothing & results in no action. Let me know if you want a sysinfo or similiar.

Thanks

**Comment by danielchalmers** [comment]
Hi @Barkingmad15, thank you very much for your kind words and detailed report, glad you are liking the program so far!

I believe this issue should be fixed with 9817fd8e6490a87983266a670649047ec183ae19 in [v3.0.0-beta3](https://github.com/danielchalmers/DesktopClock/releases/tag/v3.0.0-beta3). If it's still doesn't work on the latest version (or if you were already running that version), let me know and I will try and get it solved for you!

**Comment by Barkingmad15** [comment]
Hi @danielchalmers ,

Thanks for the update. Sadly the problem still exists. If I set it up as I like it, click exit & reopen the clock it saves settings, but upon restart (of the PC) the clock is reset to it's default settings. Oddly enough it does start with PC though with the flag 'start with PC' unchecked. Also upon initial start it flags MS Smart Screen & I had to click run anyway, it only does this the once. It may be something local to my machine, the only thing I can think of is the beta of Microsoft's PC Manager, which for some reason initially disabled auto start & had to manually disable that option. Otherwise can't think of anything out the ordinary that im running. Let me know if you want any logs.

Thanks

**Comment by danielchalmers** [comment]
Just to confirm: it's installed to `%localappdata%\DesktopClock`, and that folder contains a `DesktopClock.exe` and `DesktopClock.settings`?

Does it still reset if you turn off `Start with PC` and run DesktopClock manually after a reboot instead?

Do you have any aggressive antivirus running? And what version of Windows reported by `winver`?

Thanks. Very strange.

**Comment by danielchalmers** [comment]
That's so odd. Does it still happen if you disable the antivirus?

I wonder if this would be a workaround: turn off `Start with PC`, then make a shortcut to `DesktopClock.exe` and place it inside the `shell:startup` folder so it runs that shortcut on startup.

**Comment by Barkingmad15** [comment]
We have a winner! It's odd you suggest that, I thought last night when I shut my PC down I should try placing a shortcut in the startup folder. Anyway, it works perfectly like that with all settings retained. Trouble is, if you're like me that will bug you now as to why :) 

Thanks for a great app & your hard work :)

Anthony

**Comment by danielchalmers** [comment]
I took another look and realized it was looking for the settings file in the wrong place. Should be fixed with b079734c5ab21f99bc9dd3682dd192a4abaac631, and I'll put out a new version next week. Thank you again for the help testing this problem so it could get fixed, I really do appreciate it! @Barkingmad15
